{{- if .Values.redis.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "proxy-hopper.redisFullname" . }}
  labels:
    {{- include "proxy-hopper.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  clusterIP: None
  ports:
    - port: 6379
      targetPort: redis
      protocol: TCP
      name: redis
  selector:
    {{- include "proxy-hopper.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: redis
{{- end }}
