apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: proxy-hopper-test

resources:
  - namespace.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - servicemonitor.yaml
  - ingress.yaml

configMapGenerator:
  - name: proxy-hopper-grafana-dashboards
    options:
      disableNameSuffixHash: true
      labels:
        grafana_dashboard: "1"
        app.kubernetes.io/name: proxy-hopper
        environment: test
    files:
      - ../examples/kubernetes/dashboards/proxy-hopper-admin.json
      - ../examples/kubernetes/dashboards/proxy-hopper-user.json
